#pragma once

#ifndef	BICS_VERSION_INCLUDED
#define BICS_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define BICS_VERSION_MAJOR		1
#define BICS_VERSION_MINOR		0
#define BICS_VERSION_PATCH		0
#define BICS_VERSION_BETA		0
#define BICS_VERSION_VERSTRING	MAKE_STR(BICS_VERSION_MAJOR) "." MAKE_STR(BICS_VERSION_MINOR) "." MAKE_STR(BICS_VERSION_PATCH) "." MAKE_STR(BICS_VERSION_BETA)

#endif
